// Generated by CoffeeScript 1.7.1
(function() {
  var R, toDeg, toRad;

  R = 6371.0;

  toRad = function(deg) {
    return deg * (Math.PI / 180.0);
  };

  toDeg = function(rad) {
    return rad / (Math.PI / 180.0);
  };

  this.offsetHeading = function(brng, hdgOff) {
    return ((brng + hdgOff) + 360.0) % 360.0;
  };

  this.getHeading = function(start, end) {
    var dlon, lat1, lat2, x, y;
    dlon = toRad(end.lng - start.lng);
    lat1 = toRad(start.lat);
    lat2 = toRad(end.lat);
    x = Math.sin(dlon) * Math.cos(lat2);
    y = Math.cos(lat1) * Math.sin(lat2) - Math.sin(lat1) * Math.cos(lat2) * Math.cos(dlon);
    return (toDeg(Math.atan2(x, y)) + 360.0) % 360.0;
  };

  this.getDistance = function(start, end) {
    var a, c, dlat, dlon, lat1, lat2;
    dlat = toRad(end.lat - start.lat);
    dlon = toRad(end.lng - start.lng);
    lat1 = toRad(start.lat);
    lat2 = toRad(end.lat);
    a = Math.sin(dlat / 2.0) * Math.sin(dlat / 2.0) + Math.sin(dlon / 2.0) * Math.sin(dlon / 2.0) * Math.cos(lat1) * Math.cos(lat2);
    c = 2.0 * Math.atan2(Math.sqrt(a), Math.sqrt(1.0 - a));
    return R * c;
  };

}).call(this);
