// Generated by CoffeeScript 1.7.1
(function() {
  var fs, htrq, path;

  htrq = require("http-request");

  path = require("path");

  fs = require("fs");

  this.downloadToFile = function(url, completion) {
    var dir, getRandomFilename, imageId, name, options;
    options = {
      url: url.toString()
    };
    dir = path.join(__dirname, "../public/pics/");
    imageId = 0;
    getRandomFilename = function() {
      imageId = Math.floor(Math.random() * 10000000000);
      return "" + dir + imageId + ".jpg";
    };
    name = getRandomFilename();
    while (fs.existsSync(name)) {
      name = getRandomFilename();
    }
    return htrq.get(options, name, (function(_this) {
      return function(error, result) {
        if (error != null) {
          return completion(error, null);
        } else {
          return completion(null, imageId);
        }
      };
    })(this));
  };

}).call(this);
