// Generated by CoffeeScript 1.7.1
(function() {
  this.endWithError = function(res, err) {
    var errText, _ref;
    errText = (_ref = err.message) != null ? _ref : err;
    res.writeHead(500, {
      'Error-Text': errText
    });
    return res.end();
  };

}).call(this);
